# 标题后缀
title_suffix: 红酒室

default_keywords: 红酒室
default_description: 红酒室

successfully_creating_order: 
  success: 成功创建订单。我们会在48小时内发货。
  options:
    positionClass: "toast-top-full-width" # 样式，位于页顶
    timeOut: 180000 # 时间，毫秒

# 配送方式
delivery:
  free_if_over:               # 唯一的配送名
    name: 满200元免普通货运运费  # 显示名
    fee: 0.00                 # 配送费用
    min: 200.00               # 门槛，总金额等于或超过这个数字才可以使用
  normal:
    name: 普通货运：全顺德范围配送统一不限重，48小时内送货上门。（¥6.00）
    fee: 6.00
    max: 200.00               # 上限，总金额小于这个数字才可以使用
  fastest:
    name: 半日达：每天下午3点前下单，4小时内送达。（¥30.00）
    fee: 30.00

# 默认的订单状态
statuses:
  - 等待买家付款
  - 等待卖家发货
  - 等待买家收货
  - 买家已取消
  - 卖家已取消
  - 交易成功

# 当订单状态是如下任一状态时，改订单可被用户取消
cancelable_statuses:
  - 等待买家付款
  - 等待卖家发货

# 取消订单的原因
reasons_to_cancel:
  - 资料填写错误
  - 发现现在不需要购买
  - 已去别的地方购买

# 选择货到付款的初始订单状态
cod_initial_status: 等待卖家发货

# 选择其他支付方式的初始订单状态
payment_initial_status: 等待买家付款

# 买家取消订单后，订单的状态
buyer_cancel_status: 买家已取消

# 管理员所有订单页默认不显示下列状态的订单
default_statuses_not_to_show:
  - 买家已取消
  - 卖家已取消
  - 交易成功

# 启用发票功能
invoice_enabled: false

# 预设的快递公司
express_companies:
  顺丰: http://sf-express.com/
  韵达: http://www.yundaex.com/
  圆通: http://www.yto.net.cn/
  申通: http://www.sto.cn/
  EMS: http://www.ems.com.cn/

# 管理员账户
admins:
  - username: caiguanhao
    password: $2a$10$RGioxd1LvP0oCZJXSEakpuSsv95kRIRaDoJKnNJ9H9sK4tfpNFpeC
  - username: 8wine
    password: $2a$10$0SnMDzct4H/gtEvHOIa/TOsIkqV.cEmwTbZtY8m0HOnmZlZFvd5KK
