意大利:
  魔帽气泡酒:
    name: 意大利魔帽气泡酒

    title: 意大利魔帽气泡酒
    subtitle: 意大利魔帽气泡酒

    price: 99.9

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      
      
wine:
  ph-gran-reserva:
    name: 百高珍藏干红葡萄酒

    title: 百高珍藏干红葡萄酒
    subtitle: PH Gran Reserva

    price: 99.9

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  tierrallana:
    name: 大丰收干红葡萄酒

    title: 大丰收干红葡萄酒
    subtitle: Tierrallana

    price: 99.9

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  principe-lucas:
    name: 卢卡斯王子半干红葡萄酒

    title: 卢卡斯王子半干红葡萄酒
    subtitle: Principe Lucas

    price: 99.9

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
