wine:
  el-brusco:
    name: 意大利魔帽气泡酒

    title: 意大利魔帽气泡酒
    subtitle: EL Brusco
    shopid: IT0001
    original_price: 130
    price: 130

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    side_html: |
      <img style="border: 1px solid #CCC;" src="/photos/mmbqp.png" width="330" height="330">

    recommendations:
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva
      - /wine/ph-gran-reserva

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      
      
  ph-gran-reserva:
    name: 百高珍藏干红葡萄酒

    title: 百高珍藏干红葡萄酒
    subtitle: PH Gran Reserva
    shopid: SP0011
    original_price: 580
    price: 580

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  tierrallana:
    name: 大丰收干红葡萄酒

    title: 大丰收干红葡萄酒
    subtitle: Tierrallana
    shopid: SP0001
    original_price: 75
    price: 75

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  principe-lucas:
    name: 卢卡斯王子半干红葡萄酒

    title: 卢卡斯王子半干红葡萄酒
    subtitle: Principe Lucas
    shopid: SP0002
    original_price: 118
    price: 118

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  antano-08:
    name: 第一庄08

    title: 第一庄08
    subtitle: Antano
    shopid: SP0003
    original_price: 200
    price: 200

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      
      
  antano-05:
    name: 第一庄05

    title: 第一庄05
    subtitle: Antano
    shopid: SP0004
    original_price: 320
    price: 320

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  sierra-de-viento:
    name: 风神干红葡萄酒

    title: 风神干红葡萄酒
    subtitle: Sierra de Viento
    shopid: SP0005
    original_price: 150
    price: 150

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  el-sotillo:
    name: 苏提乐干红葡萄酒

    title: 苏提乐干红葡萄酒
    subtitle: EL Sotillo
    shopid: SP0006
    original_price: 68
    price: 68

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      
      
  marques-de-la-gruh:
    name: 克鲁斯伯爵白气泡葡萄酒

    title: 克鲁斯伯爵白气泡葡萄酒
    subtitle: Marques de la Gruh
    shopid: SP0008
    original_price: 120
    price: 120

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      
      
  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
      

  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍


  jaume-serra:
    name: 佐米cava气泡酒

    title: 佐米cava气泡酒
    subtitle: Jaume Serra
    shopid: SP0009
    original_price: 160
    price: 160

    images:
      - /photos/mmbqp.png

    slides:
      - /photos/mmbqp.png

    商品描述: |
      **名称：**
      
      ![图片](/photos/mmbqp.png)
      
      **描述：**
      
      气泡酒又名起泡酒或汽酒，因酒中含有一定数量的二氧化碳形成气泡。二氧化碳通过酒的发酵在瓶内或大型储酒缸中自然形成，或被注入酒中。气泡酒通常是白色或粉红色的，但如意大利和澳大利亚等国也分别用布拉凯托红葡萄和西拉红葡萄酿造红色的气泡酒。气泡酒可根据含糖量分为干型、甜型等不同等级。

    酒庄介绍: |
      酒庄介绍
